# Generated by Django 4.1.7 on 2023-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_envoie',
            field=models.DateField(auto_now=True),
        ),
    ]
