# Generated by Django 3.2.12 on 2023-07-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionCollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temps', models.IntegerField()),
            ],
            options={
                'db_table': 'fonction',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenoms', models.CharField(max_length=20)),
                ('biographie', models.CharField(max_length=500)),
                ('piece_jointe', models.CharField(max_length=500)),
                ('date_demande', models.DateTimeField()),
                ('date_fin', models.DateTimeField(null=True)),
                ('etat', models.IntegerField()),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fonctioncollab')),
            ],
            options={
                'db_table': 'collaboration',
            },
        ),
    ]
