# Generated by Django 4.2 on 2023-06-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_envoie',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
