# Generated by Django 3.2.12 on 2023-07-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_collaboration_fonctioncollab'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDocteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('collaboration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collaboration')),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.specialite')),
            ],
            options={
                'db_table': 'demande_docteur',
            },
        ),
    ]
