# Generated by Django 4.2 on 2023-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_message_date_envoie_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_de_naissance',
            field=models.DateField(),
        ),
    ]
