# Generated by Django 3.2.12 on 2023-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historiquepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
