# Generated by Django 3.2.12 on 2023-07-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_demandedocteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedocteur',
            name='etat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
