# Generated by Django 3.2.12 on 2023-06-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medecin_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquepatient',
            old_name='date_modif',
            new_name='date_suppression',
        ),
    ]
