# Generated by Django 3.2.12 on 2023-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_modif_historiquepatient_date_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
