# Generated by Django 3.2.12 on 2023-07-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='heure_rdv',
            new_name='dateHeure_rdv',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='date_rdv',
        ),
    ]
