# Generated by Django 3.2.12 on 2023-07-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230701_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='dateHeure_rdv',
            new_name='dateheure_rdv',
        ),
    ]
