# Generated by Django 3.2.12 on 2023-07-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_dateheure_rdv_rdv_dateheure_rdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionCollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fonction',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenoms', models.CharField(max_length=20)),
                ('biographie', models.CharField(max_length=500)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fonctioncollab')),
            ],
            options={
                'db_table': 'collaboration',
            },
        ),
    ]
