# Generated by Django 3.2.12 on 2023-07-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_collaboration_fonctioncollab'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctioncollab',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
