# Generated by Django 3.2.12 on 2023-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fonctioncollab_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='etat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
