# Generated by Django 3.2.12 on 2023-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_collaboration_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='piece_jointe',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
