# Generated by Django 3.2.12 on 2023-07-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_collaboration_piece_jointe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='piece_jointe',
            field=models.CharField(max_length=500),
        ),
    ]
