# Generated by Django 3.2.12 on 2023-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='dateDebut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='dateFin',
            field=models.DateTimeField(null=True),
        ),
    ]
